services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ldagm-app
    working_dir: /app
    command: tail -f /dev/null
    volumes:
      - .:/app
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    stdin_open: true
    tty: true
